# Generated by Django 5.2.7 on 2025-10-29 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstAppDjango', '0003_user_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='color_palette',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
