# Generated by Django 5.2.7 on 2025-10-27 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstAppDjango', '0003_artwork_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='quantity_initial',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
