# Generated by Django 5.2.7 on 2025-10-29 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstAppDjango', '0004_artwork_color_palette'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='artwork_mood',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
