# Generated by Django 5.2.7 on 2025-10-30 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FirstAppDjango', '0004_eventparticipant_workshopparticipant'),
        ('FirstAppDjango', '0005_artwork_artwork_mood'),
    ]

    operations = [
    ]
