# Generated by Django 5.2.7 on 2025-10-28 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstAppDjango', '0005_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='moderation_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='moderation_status',
            field=models.CharField(choices=[('pending', 'En attente de modération'), ('approved', 'Approuvé'), ('rejected', 'Rejeté'), ('flagged', 'Marqué pour révision')], default='pending', max_length=20),
        ),
    ]
