# Generated by Django 5.2.7 on 2025-10-29 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FirstAppDjango', '0006_comment_moderation_reason_comment_moderation_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='likes',
        ),
    ]
