# Generated by Django 5.2.7 on 2025-10-30 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstAppDjango', '0006_merge_20251030_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='artistic_nickname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
