# Generated by Django 5.2.7 on 2025-10-30 22:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstAppDjango', '0007_auto_20251030_2219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artwork',
            name='artwork_mood',
        ),
        migrations.AlterField(
            model_name='user',
            name='category',
            field=models.CharField(choices=[('Visiteur', 'Visiteur'), ('Artist', 'Artist')], default='Visiteur', max_length=20),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='duration',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('artwork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='FirstAppDjango.artwork')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
